A function or procedure are use to avoid code repetition.

We can either return a value after an operation (in this case it is a function)

Or do an execution without returning anything (then it is a procedure)

to declare a function or procedure we use the keyword : def

the keyword return will be use to return something from the function.

In [1]:
def my_procedure():
    print("call to my_procedure")

def my_function():
    return "call to my_function"

my_procedure()

print(my_function())

call to my_procedure
call to my_function


We can also pass arguments to the function by placing them inside the parenthesis :

In [2]:
def add(x, y):
    return x + y

print(add(5, 9))

14


In [3]:
def potential_energy(mass, height, g):
    return mass * height * g

print(potential_energy(5, 5, 9.81), "J")

245.25 J


# Lambda 

lambda expressions are small functions declared without def, we will then use lambda to declare it and to put it inside a variable.

In [4]:
f = lambda x, y: x + y
print(f(7, 9)) 

16


These are often use to declare mathematical functions : 

In [5]:
f = lambda x, y: x ** 2 + y
print(f(5, 6))

31


In [6]:
print(type(f))
print(type(my_function))

<class 'function'>
<class 'function'>


# Default parameters

we can set part or all of our variable with default values.

Using default values for all parameter is not recommanded.

In [7]:
def potential_energy(mass, height, g = 9.81):
    print(f"Mass : {mass}, height : {height} g : {g}")
    return mass * height * g

print(potential_energy(5, 10), "J")

Mass : 5, height : 10 g : 9.81
490.5 J


We can also call a function and use the name of the args to pass their values :

In [8]:
print(potential_energy(height=10, mass=5), "J")

Mass : 5, height : 10 g : 9.81
490.5 J


# Useful built in function

<a href="https://docs.python.org/3/library/functions.html">doc</a>

In [9]:
x = -5

abs(x)

5

In [10]:
x = 3.1415

round(x)

3

In [11]:
list1 = [52, 41, 32, 96, 0]

max(list1)

96

In [12]:
min(list1)

0

In [13]:
len(list1)

5

In [14]:
sum(list1)

221

In [15]:
any(list1) # return True if at least one element is true or > 0

True

In [16]:
all(list1) # return true if all are true of > 0

False

# FORMAT AND CASTING

## format

bin()
byte()
hex() 
oct()

## Data structure

dict()
list()
tupe()
set()

## Variable type

float()
int()
str()

type()


In [17]:
x = 10
type(x)

int

In [18]:
type(float(x))

float

In [19]:
str(x)

'10'

In [20]:
y = "20"
int(y)

20

In [21]:
y = "20.5"
float(y)

20.5

In [22]:
y = "will this crash?"
float(y)

ValueError: could not convert string to float: 'will this crash?'

In [25]:
list1 = [5, 6, 1, 3, 9]
tup = tuple(list1)
print(tup)
list2 = list(tup)
print(list2)

(5, 6, 1, 3, 9)
[5, 6, 1, 3, 9]


## Number Format

In [27]:
x = 951
print(bin(x))
print(hex(x))
print(oct(x))

0b1110110111
0x3b7
0o1667


# INPUT

In [30]:
input("Enter something : ")

'123'

In [31]:
x = input("Enter something an integer : ")
print(x)
print(type(x))

321
<class 'str'>


In [32]:
x = int(x)
print(x)
print(type(x))

321
<class 'int'>


## FORMAT

In [33]:
x = 20
town = "Brussels"

print("x°C at town")
print("{}°C at {}".format(x, town))
print(f"{x}°C at {town}")

x°C at town
20°C at Brussels
20°C at Brussels


In [34]:
import numpy as np

In [37]:
params = {
        "W1": np.random.randn(2, 4),
        "b2": np.zeros((2, 4)),
        "W2": np.random.randn(2, 2),
        "b2": np.zeros((2, 1))
    }

for i in range(1, 3):
    print(i)
    print(params[f"W{i}"])

1
[[-1.40849445  0.0220067  -0.83851016  1.37699064]
 [-0.75582613 -0.30047213  0.09918004 -0.81304331]]
2
[[-0.17212887  1.88493408]
 [-1.29877898 -0.26314233]]


# OPEN

In [44]:
file = open('myFile.txt', 'a')
if(file.writable()):
    file.write("I want to add this line!\n")

file.close()

file = open('myFile.txt', 'r')
file.readlines()
file.close()

['I want to add this line!\n',
 'I want to add this line!\n',
 'I want to add this line!\n',
 'I want to add this line!\n']

In [46]:
with open('myFile.txt', 'r') as f:
    print(f.readline())

# automatically closed!


I want to add this line!

