# N-dimensional array

Smaller in size => faster

A lot of useful functions that are already implemented for us.

arr.shape!!! It return a tuple !!! so we can access the tuple with [] [0] for row, [1] for columns



In [1]:
import numpy as np

In [3]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [7]:
A.shape

(3,)

In [8]:
A.ndim

1

In [11]:
np.zeros((3,3)) # able us to create empty arrays, pretty useful in data science when we want to create a new array to fill later on.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
B = np.ones((4,4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
B.shape

(4, 4)

In [15]:
C = np.full((2, 3), 7)
C

array([[7, 7, 7],
       [7, 7, 7]])

In [16]:
np.random.randn(4, 5) # standard normal distribution centered on 0

array([[-0.08777639, -0.31796961, -1.10598559, -0.76993346, -2.06369047],
       [-0.04225924, -0.14187113, -0.69494808,  0.51343256, -0.10036607],
       [-1.25620765, -1.00372069, -1.2792274 , -0.42490899, -0.61825207],
       [-1.74885542, -0.30323147,  0.72306591, -1.19371571, -1.02869897]])

In [17]:
np.random.seed(2)
np.random.randn(4, 5)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801,  0.04153939, -1.11792545,  0.53905832],
       [-0.5961597 , -0.0191305 ,  1.17500122, -0.74787095,  0.00902525]])

In [18]:
np.eye(4) # Create an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.linspace(0, 10, 5) # create an 1D array with a start value and an end value, and the quantity of split desired

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.arange(0, 10, 2) # Here instead of the desired split we enter the value between steps.

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(0, 10, 5, dtype=np.int8) # dtype able us to set a data type

array([ 0,  2,  5,  7, 10], dtype=int8)

In [28]:
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [29]:
np.linspace(0, 10, 20, dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Transformation

In [40]:
A = np.zeros((3, 2))
A2 = np.zeros((3))
B = np.ones((3,2))
B2 = np.ones((2))

In [41]:
C = np.hstack((A, B))
print(C)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [48]:
D = np.vstack((A, B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
np.concatenate((A, B), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
np.concatenate((A, B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [51]:
#D = np.hstack((A, B2))
#D

In [53]:
D.reshape((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
A3 = np.array([1, 2, 3])
# some algorithm will require both dimensions to be set
A3.shape

(3,)

In [57]:
A3 = A3.reshape(A3.shape[0], 1) # sometime this will be require when we do compute some matrix or use some specific functions we will see later on.
A3

array([[1],
       [2],
       [3]])

In [59]:
# sometime we can have the same problem but instead of wanting the 1 dimension to be shown we wan to hide it.
# then we can use 

A4 = A3.squeeze() # Squeez will delete all the dimension with only a 1.
A4.shape

(3,)

In [61]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
D.ravel() # ravel the array so here this will return a 1D array

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [64]:
D2 = np.ones((3, 3, 3))
D2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
D2.ravel() # We will see how that this will also be useful for some future algorithm.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
def exercice(m, n):
    E1 = np.random.randn(m, n)
    E2 = np.ones((m, 1))
    print(np.concatenate((E1, E2), axis=1))

exercice(3, 4)

[[ 1.27837923 -0.63467931  0.50839624  0.21611601  1.        ]
 [-1.85861239 -0.41931648 -0.1323289  -0.03957024  1.        ]
 [ 0.32600343 -2.04032305  0.04625552 -0.67767558  1.        ]]
